### PR TITLE
If there is 0 notifications, do not show red badge

### PR DESCRIPTION
**Pull request by umpirsky**
It's eye catcher, we don't need it if 0 notifications.

screenshot from 2018-01-09 12-21-58

### CODE REVIEW

**Comment by umpirsky** [comment]
@AngelFQC Ping. :)

**Comment by AngelFQC** [comment]
This weekend new version 😃

**Comment by AngelFQC** [comment]
I am accepting this PR, but moving the lines of code upwards for a better understanding.
Here 24ac777d907ccfdaf63457935a426814ff1efbd9

Thanks

**Comment by umpirsky** [comment]
@AngelFQC How to get update? Is it released?

**Comment by AngelFQC** [comment]
@umpirsky No, I want to fix #4 to publish a release

**Pull request merged**
